name: CustomForm
version: 0.1
main: AhmetAB01\CustomForm\Main
src-namespace-prefix: AhmetAB01\CustomForm
api: 4.0.0
author: Ryzwe
permissions:
  customform.command:
    description: "Insufficient Authorization"
    default: true
