name: CustomForm
main: AhmetAB01\CustomForm\Main
author: Ryzwe
src-namespace-prefix: AhmetAB01\CustomForm
api: 4.0.0
version: 0.1
commands:
  customform:
    description: ยง3Form
    permission: customform.use
    
    
permissions:
  customform.use:
    description: "Insufficient Authorization"
    default: true
